name: Correct Robot
on: workflow_dispatch
permissions:
  contents: write
jobs:
  corrector:
    runs_on: ubuntu_latest
    steps:
      - uses: actions/checkout@v5
      - name: file generate
        run: echo "test"
      - name: Commit & push
        run: echo "commit & push"
