name: Correct Robot 
on: workflow_dispatch
permissions:
  contents: write
jobs:
  corrector:
    runs_on: ubuntu_latest
    steps:
      -users: actions/checkout@v5
      -name: file generate
      run: date "+Last build: %d/%m/%y %H:%M UTC " > Lastbuild.txt
      -name: Commit & push 
      run: git config user.name "github_actions[bot]"
      git config user.mail "github_actions[bot]@users.noreply.github.com"
      git add lastbuild.txt
      git commit -m "auto update" || echo "nothing to commit"
      git push 
